#!/bin/bash
/usr/bin/dwm-panel start

# Black background
xsetroot -solid black

xrdb -merge ~/.Xresources &

# Fix Java apps but break Google Chrome bookmarks menu
#wmname LG3D
# Launch DBus if needed
if which dbus-launch >/dev/null && test -z "$DBUS_SESSION_BUS_ADDRESS"; then
    eval "$(ck-launch-session dbus-launch --sh-syntax --exit-with-session)"
    #eval "$(dbus-launch --sh-syntax --exit-with-session)"
fi
# Start polkit agent
/usr/libexec/lxpolkit &

# Start $HOME/.dwm-start if exists
test -e $HOME/.dwm-start && $HOME/.dwm-start &

while true; do
    dwm || { /usr/bin/dwm-panel stop; exit; }
done
